if(NOT DEFINED SIGNAL_SYNTH_CLI OR NOT DEFINED SIGNAL_SYNTH_EXAMPLE OR NOT DEFINED SIGNAL_SYNTH_PPG_EXAMPLE OR NOT DEFINED SIGNAL_SYNTH_PACK_EXAMPLE OR NOT DEFINED SIGNAL_SYNTH_CLI_WORK_DIR)
    message(FATAL_ERROR "CLI test paths are not configured")
endif()

file(REMOVE_RECURSE "${SIGNAL_SYNTH_CLI_WORK_DIR}")
file(MAKE_DIRECTORY "${SIGNAL_SYNTH_CLI_WORK_DIR}")

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" validate "${SIGNAL_SYNTH_EXAMPLE}" RESULT_VARIABLE validate_result OUTPUT_VARIABLE validate_output ERROR_VARIABLE validate_error)
if(NOT validate_result EQUAL 0 OR NOT validate_error STREQUAL "" OR NOT validate_output MATCHES "^status=valid")
    message(FATAL_ERROR "Valid scenario validation failed: ${validate_error}")
endif()

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" fingerprint "${SIGNAL_SYNTH_EXAMPLE}" RESULT_VARIABLE fingerprint_result OUTPUT_VARIABLE fingerprint_output ERROR_VARIABLE fingerprint_error)
if(NOT fingerprint_result EQUAL 0 OR NOT fingerprint_error STREQUAL "" OR NOT fingerprint_output MATCHES "^document_fingerprint=sha256:[0-9a-f]+")
    message(FATAL_ERROR "Scenario fingerprint command failed: ${fingerprint_error}")
endif()

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" validate - INPUT_FILE "${SIGNAL_SYNTH_EXAMPLE}" RESULT_VARIABLE stdin_result OUTPUT_VARIABLE stdin_output ERROR_VARIABLE stdin_error)
if(NOT stdin_result EQUAL 0 OR NOT stdin_error STREQUAL "" OR NOT stdin_output STREQUAL validate_output)
    message(FATAL_ERROR "stdin validation differs from file validation")
endif()

set(invalid_file "${SIGNAL_SYNTH_CLI_WORK_DIR}/invalid.json")
file(WRITE "${invalid_file}" "{\"schema_version\":1}")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" validate "${invalid_file}" RESULT_VARIABLE invalid_result OUTPUT_VARIABLE invalid_output ERROR_VARIABLE invalid_error)
if(NOT invalid_result EQUAL 4 OR NOT invalid_output STREQUAL "" OR NOT invalid_error MATCHES "^error=SCENARIO_JSON_MISSING_FIELD")
    message(FATAL_ERROR "Invalid scenario error contract failed")
endif()

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" validate "${SIGNAL_SYNTH_CLI_WORK_DIR}/missing.json" RESULT_VARIABLE missing_result OUTPUT_VARIABLE missing_output ERROR_VARIABLE missing_error)
if(NOT missing_result EQUAL 3 OR NOT missing_output STREQUAL "" OR NOT missing_error MATCHES "^error=INPUT_READ_FAILED")
    message(FATAL_ERROR "Missing-file error contract failed")
endif()

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" unknown "${SIGNAL_SYNTH_EXAMPLE}" RESULT_VARIABLE usage_result OUTPUT_VARIABLE usage_output ERROR_VARIABLE usage_error)
if(NOT usage_result EQUAL 2 OR NOT usage_output STREQUAL "" OR NOT usage_error MATCHES "^usage:")
    message(FATAL_ERROR "Usage error contract failed")
endif()

set(render_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/render")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" render "${SIGNAL_SYNTH_EXAMPLE}" --out "${render_dir}" RESULT_VARIABLE render_result OUTPUT_VARIABLE render_output ERROR_VARIABLE render_error)
if(NOT render_result EQUAL 0 OR NOT render_error STREQUAL "" OR NOT render_output MATCHES "^status=rendered" OR NOT EXISTS "${render_dir}/report.html" OR NOT EXISTS "${render_dir}/waveform.csv" OR NOT EXISTS "${render_dir}/synsigra.hea" OR NOT EXISTS "${render_dir}/synsigra.dat" OR NOT EXISTS "${render_dir}/synsigra.atr" OR NOT EXISTS "${render_dir}/synsigra.edf" OR NOT EXISTS "${render_dir}/synsigra.bdf")
    message(FATAL_ERROR "CLI render contract failed: ${render_error}")
endif()
file(READ "${render_dir}/annotations.json" render_annotations)
string(REGEX MATCHALL "\"r_peak_seconds\":[0-9.eE+-]+" render_r_peak_fields "${render_annotations}")
file(READ "${render_dir}/hrv_metrics.json" render_hrv_metrics)
string(REGEX MATCH "\"mean_rr_seconds\":([0-9.eE+-]+)" render_mean_rr "${render_hrv_metrics}")
if(NOT render_mean_rr)
    message(FATAL_ERROR "Rendered HRV metrics contain no mean RR")
endif()
set(hrv_user_file "${SIGNAL_SYNTH_CLI_WORK_DIR}/hrv_user_output.json")
file(WRITE "${hrv_user_file}" "{\"schema_version\":1,\"algorithm\":{\"name\":\"cli_hrv_smoke\",\"version\":\"1\"},\"metrics\":{\"mean_rr_seconds\":${CMAKE_MATCH_1}}}")
set(hrv_score_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/hrv_score")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" hrv score "${SIGNAL_SYNTH_EXAMPLE}" "${hrv_user_file}" --out "${hrv_score_dir}" RESULT_VARIABLE hrv_score_result OUTPUT_VARIABLE hrv_score_output ERROR_VARIABLE hrv_score_error)
if(NOT hrv_score_result EQUAL 0 OR NOT hrv_score_error STREQUAL "" OR NOT hrv_score_output MATCHES "^status=hrv-scored" OR NOT hrv_score_output MATCHES "metric_pass_fraction=1" OR NOT EXISTS "${hrv_score_dir}/hrv_score.json" OR NOT EXISTS "${hrv_score_dir}/hrv_score.csv" OR NOT EXISTS "${hrv_score_dir}/hrv_score_report.html")
    message(FATAL_ERROR "CLI HRV score contract failed: ${hrv_score_error}")
endif()
set(compare_detection_file "${SIGNAL_SYNTH_CLI_WORK_DIR}/r_peak_detections.csv")
file(WRITE "${compare_detection_file}" "time_seconds,label\n")
foreach(field ${render_r_peak_fields})
    string(REPLACE "\"r_peak_seconds\":" "" r_peak_time "${field}")
    file(APPEND "${compare_detection_file}" "${r_peak_time},r\n")
endforeach()
set(compare_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/compare")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" compare rpeaks "${SIGNAL_SYNTH_EXAMPLE}" "${compare_detection_file}" --out "${compare_dir}" RESULT_VARIABLE compare_result OUTPUT_VARIABLE compare_output ERROR_VARIABLE compare_error)
if(NOT compare_result EQUAL 0 OR NOT compare_error STREQUAL "" OR NOT compare_output MATCHES "^status=compared" OR NOT compare_output MATCHES "f1_score=1" OR NOT EXISTS "${compare_dir}/comparison.json" OR NOT EXISTS "${compare_dir}/comparison.csv" OR NOT EXISTS "${compare_dir}/comparison_report.html")
    message(FATAL_ERROR "CLI compare contract failed: ${compare_error}")
endif()
set(compare_detection_json "${SIGNAL_SYNTH_CLI_WORK_DIR}/r_peak_detections.json")
file(WRITE "${compare_detection_json}" "{\"schema_version\":1,\"algorithm\":{\"name\":\"cli_json_smoke\",\"version\":\"1\"},\"target\":\"r_peak\",\"events\":[")
set(json_separator "")
foreach(field ${render_r_peak_fields})
    string(REPLACE "\"r_peak_seconds\":" "" r_peak_time "${field}")
    file(APPEND "${compare_detection_json}" "${json_separator}{\"time_seconds\":${r_peak_time},\"label\":\"r\"}")
    set(json_separator ",")
endforeach()
file(APPEND "${compare_detection_json}" "]}")
set(compare_json_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/compare_json")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" compare rpeaks "${SIGNAL_SYNTH_EXAMPLE}" "${compare_detection_json}" --out "${compare_json_dir}" RESULT_VARIABLE compare_json_result OUTPUT_VARIABLE compare_json_output ERROR_VARIABLE compare_json_error)
if(NOT compare_json_result EQUAL 0 OR NOT compare_json_error STREQUAL "" OR NOT compare_json_output MATCHES "^status=compared" OR NOT compare_json_output MATCHES "f1_score=1" OR NOT EXISTS "${compare_json_dir}/comparison.json")
    message(FATAL_ERROR "CLI JSON compare contract failed: ${compare_json_error}")
endif()
set(beat_class_json "${SIGNAL_SYNTH_CLI_WORK_DIR}/beat_classifications.json")
file(WRITE "${beat_class_json}" "{\"schema_version\":1,\"algorithm\":{\"name\":\"cli_beat_class_smoke\",\"version\":\"1\"},\"target\":\"ecg_beat_classification\",\"events\":[")
set(json_separator "")
foreach(field ${render_r_peak_fields})
    string(REPLACE "\"r_peak_seconds\":" "" r_peak_time "${field}")
    file(APPEND "${beat_class_json}" "${json_separator}{\"time_seconds\":${r_peak_time},\"label\":\"normal\"}")
    set(json_separator ",")
endforeach()
file(APPEND "${beat_class_json}" "]}")
set(beat_class_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/beat_class_compare")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" compare beat-classes "${SIGNAL_SYNTH_EXAMPLE}" "${beat_class_json}" --out "${beat_class_dir}" RESULT_VARIABLE beat_class_result OUTPUT_VARIABLE beat_class_output ERROR_VARIABLE beat_class_error)
if(NOT beat_class_result EQUAL 0 OR NOT beat_class_error STREQUAL "" OR NOT beat_class_output MATCHES "^status=compared" OR NOT beat_class_output MATCHES "accuracy=1" OR NOT beat_class_output MATCHES "f1_score=1" OR NOT EXISTS "${beat_class_dir}/comparison.json" OR NOT EXISTS "${beat_class_dir}/comparison.csv" OR NOT EXISTS "${beat_class_dir}/comparison_report.html")
    message(FATAL_ERROR "CLI beat classification compare contract failed: ${beat_class_error}")
endif()
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" render "${SIGNAL_SYNTH_EXAMPLE}" --out "${render_dir}" RESULT_VARIABLE overwrite_result OUTPUT_VARIABLE overwrite_output ERROR_VARIABLE overwrite_error)
if(NOT overwrite_result EQUAL 3 OR NOT overwrite_output STREQUAL "" OR NOT overwrite_error MATCHES "^error=OUTPUT_WRITE_FAILED")
    message(FATAL_ERROR "CLI no-overwrite contract failed")
endif()

set(ppg_render_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/ppg_render")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" render "${SIGNAL_SYNTH_PPG_EXAMPLE}" --out "${ppg_render_dir}" RESULT_VARIABLE ppg_render_result OUTPUT_VARIABLE ppg_render_output ERROR_VARIABLE ppg_render_error)
if(NOT ppg_render_result EQUAL 0 OR NOT ppg_render_error STREQUAL "" OR NOT ppg_render_output MATCHES "document_fingerprint=sha256:ab3057597074b98e77c1d0623568ea852043b46690e728869b2b404394fe2415" OR NOT EXISTS "${ppg_render_dir}/waveform.csv")
    message(FATAL_ERROR "CLI ECG/PPG render failed: ${ppg_render_error}")
endif()
file(STRINGS "${ppg_render_dir}/waveform.csv" ppg_csv_header LIMIT_COUNT 1)
if(NOT ppg_csv_header MATCHES "ppg_green_au$")
    message(FATAL_ERROR "CLI ECG/PPG export has no PPG channel")
endif()

execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" pack validate "${SIGNAL_SYNTH_PACK_EXAMPLE}" RESULT_VARIABLE pack_validate_result OUTPUT_VARIABLE pack_validate_output ERROR_VARIABLE pack_validate_error)
if(NOT pack_validate_result EQUAL 0 OR NOT pack_validate_error STREQUAL "" OR NOT pack_validate_output MATCHES "^status=valid")
    message(FATAL_ERROR "Pack validation failed: ${pack_validate_error}")
endif()

set(pack_render_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/pack_render")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" pack render "${SIGNAL_SYNTH_PACK_EXAMPLE}" --out "${pack_render_dir}" RESULT_VARIABLE pack_render_result OUTPUT_VARIABLE pack_render_output ERROR_VARIABLE pack_render_error)
if(NOT pack_render_result EQUAL 0 OR NOT pack_render_error STREQUAL "" OR NOT pack_render_output MATCHES "^status=pack-rendered" OR NOT EXISTS "${pack_render_dir}/summary.json" OR NOT EXISTS "${pack_render_dir}/summary.csv" OR NOT EXISTS "${pack_render_dir}/index.html")
    message(FATAL_ERROR "Pack render failed: ${pack_render_error}")
endif()
set(pack_challenge_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/pack_challenge")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" pack challenge "${SIGNAL_SYNTH_PACK_EXAMPLE}" --out "${pack_challenge_dir}" RESULT_VARIABLE pack_challenge_result OUTPUT_VARIABLE pack_challenge_output ERROR_VARIABLE pack_challenge_error)
if(NOT pack_challenge_result EQUAL 0 OR NOT pack_challenge_error STREQUAL "" OR NOT pack_challenge_output MATCHES "^status=challenge-rendered" OR NOT pack_challenge_output MATCHES "package_fingerprint=sha256:[0-9a-f]+" OR NOT EXISTS "${pack_challenge_dir}/manifest.json" OR NOT EXISTS "${pack_challenge_dir}/pack.json" OR NOT EXISTS "${pack_challenge_dir}/cases/clean_70/waveform.csv" OR NOT EXISTS "${pack_challenge_dir}/cases/clean_70/annotations.json" OR NOT EXISTS "${pack_challenge_dir}/cases/clean_70/synsigra.hea" OR NOT EXISTS "${pack_challenge_dir}/cases/clean_70/synsigra.edf")
    message(FATAL_ERROR "Pack challenge render failed: ${pack_challenge_error}")
endif()
file(READ "${pack_challenge_dir}/manifest.json" pack_challenge_manifest)
if(NOT pack_challenge_manifest MATCHES "\"package_id\":\"r_peak_stress_v1\"" OR NOT pack_challenge_manifest MATCHES "\"role\":\"wfdb_header\"" OR NOT pack_challenge_manifest MATCHES "\"role\":\"edf\"" OR NOT pack_challenge_manifest MATCHES "\"sha256\":\"sha256:[0-9a-f][0-9a-f]")
    message(FATAL_ERROR "Pack challenge manifest contract failed")
endif()
set(pack_detection_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/pack_detections")
file(MAKE_DIRECTORY "${pack_detection_dir}")
foreach(case_id clean_70 slow_45 fast_120 baseline_powerline)
    file(READ "${pack_render_dir}/${case_id}/annotations.json" pack_case_annotations)
    string(REGEX MATCHALL "\"r_peak_seconds\":[0-9.eE+-]+" pack_case_r_peak_fields "${pack_case_annotations}")
    set(pack_case_detection_json "${pack_detection_dir}/${case_id}.json")
    file(WRITE "${pack_case_detection_json}" "{\"schema_version\":1,\"algorithm\":{\"name\":\"cli_pack_json_smoke\",\"version\":\"1\"},\"target\":\"r_peak\",\"events\":[")
    set(json_separator "")
    foreach(field ${pack_case_r_peak_fields})
        string(REPLACE "\"r_peak_seconds\":" "" r_peak_time "${field}")
        file(APPEND "${pack_case_detection_json}" "${json_separator}{\"time_seconds\":${r_peak_time},\"label\":\"r\"}")
        set(json_separator ",")
    endforeach()
    file(APPEND "${pack_case_detection_json}" "]}")
endforeach()
set(pack_score_dir "${SIGNAL_SYNTH_CLI_WORK_DIR}/pack_score")
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" pack score "${SIGNAL_SYNTH_PACK_EXAMPLE}" "${pack_detection_dir}" --out "${pack_score_dir}" RESULT_VARIABLE pack_score_result OUTPUT_VARIABLE pack_score_output ERROR_VARIABLE pack_score_error)
if(NOT pack_score_result EQUAL 0 OR NOT pack_score_error STREQUAL "" OR NOT pack_score_output MATCHES "^status=pack-scored" OR NOT EXISTS "${pack_score_dir}/pack_score_summary.json" OR NOT EXISTS "${pack_score_dir}/pack_score_summary.csv" OR NOT EXISTS "${pack_score_dir}/pack_score_report.html")
    message(FATAL_ERROR "Pack score failed: ${pack_score_error}")
endif()

set(large_file "${SIGNAL_SYNTH_CLI_WORK_DIR}/large.json")
set(block "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
file(WRITE "${large_file}" "")
foreach(index RANGE 0 262144)
    file(APPEND "${large_file}" "${block}")
endforeach()
execute_process(COMMAND "${SIGNAL_SYNTH_CLI}" validate "${large_file}" RESULT_VARIABLE large_result OUTPUT_VARIABLE large_output ERROR_VARIABLE large_error)
if(NOT large_result EQUAL 3 OR NOT large_output STREQUAL "" OR NOT large_error MATCHES "^error=INPUT_READ_FAILED")
    message(FATAL_ERROR "Input-size limit contract failed")
endif()
